name: Go Build and Commit

on:
  push:
    branches:
      - main  # Or your development branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2
      with:
        path: 'main_repo'
    
    - name: Clone and Build WarpGPT for Windows AMD64
      run: |
        # Clone WarpGPT repository
        git clone https://github.com/oliverkirk-sudo/WarpGPT
        cd WarpGPT
        
        # Download Go modules
        go mod download

        # Build for Windows AMD64
        GOOS=windows GOARCH=amd64 go build -o warpgpt.exe
        
        # Move the binary to the main repository directory
        mv warpgpt.exe ../main_repo/
      shell: bash

    - name: Commit and Push binary to main repository
      run: |
        cd main_repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if binary exists and commit it
        if [ -f "./warpgpt.exe" ]; then
          git add warpgpt.exe
          git commit -m "Add built binary for Windows AMD64"
          git push
        else
          echo "Binary not found, nothing to commit."
          exit 1
        fi
      shell: bash
